name: Build, Test, and Push
on: [push]
env:
  IMAGE_NAME: student_service
  REPO_NAME: frituurmandje

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Build and run services using docker compose
      - name: Build and start services with docker compose
        run: docker compose up --build -d

      # Wait for services to be fully ready (adjust the sleep time if necessary)
      - name: Wait for services to be ready
        run: sleep 10

      # Tag built image for push
      - name: Tag built image for push
        run: docker tag $IMAGE_NAME $REPO_NAME/$IMAGE_NAME:latest

      # Your other steps, such as checking files and running API tests
      - name: "Check files existence"
        uses: andstor/file-existence-action@v2
        with:
          files: "postman/collection.json,postman/environment.json"
          fail: true

      - name: Run API Tests
        id: run-newman
        uses: anthonyvscode/newman-action@master
        with:
          collection: postman/collection.json
          environment: postman/environment.json
          reporters: cli
          bail: true

      - name: Check if we failed
        id: fail-check
        shell: bash
        env:
          JSON_DOC: ${{ steps.run-newman.outputs.summary }}
        run: |
          # Write API test summary to summary.json for debugging
          printf '%s\n' "$JSON_DOC" > summary.json
          cat summary.json
          if grep -q Collection summary.json; then
            # Instead of the deprecated set-output command, write directly to $GITHUB_OUTPUT
            echo "failed=false" >> $GITHUB_OUTPUT
          else
            echo "failed=true" >> $GITHUB_OUTPUT
          fi

      - name: Fail if tests failed
        if: ${{ steps.fail-check.outputs.failed == 'true' }}
        run: exit 1

      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push image to Docker Hub Container Registry
        run: docker push $REPO_NAME/$IMAGE_NAME

      # Optionally, bring down the docker compose services
      - name: Tear down docker compose services
        run: docker compose down
